# Generated by Django 4.0.5 on 2022-07-31 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='translation_url',
            new_name='files_url',
        ),
    ]
